# -*- coding: utf-8 -*-
"""intrminedadosava1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VJQh7w3hUatUWJemGB3MXpq7MnNlj8k7
"""

import random as rnd
import itertools as it
from itertools import ( starmap, combinations, repeat)
from operator import getitem

def geradorHipoteses(nvariaveis, max_value ):
  #Objetivo: agrupar o valor das variáveis apresentadas e informar todas as
  # conjuções com até 3 variáveis (incluindo sua negação).
  variaveis = list()
  for p in range (1, nvariaveis+1):
    # Laço que gera as variaveis acompanhadas de seu numerador correspondente
    x = "x" + str(p)
    negx = "¬" + x
    variaveis.append(x)
    variaveis.append(negx)
    hipoteses = list()
  # Laço para definir o valor de combinações das variaveis

  for tamanho in range(1, max_value + 1):
        hipoteses.extend(combinations(variaveis, tamanho))


  return hipoteses

# Exemplo de uso para demonstrar os resultados:
x = geradorHipoteses(4,3)
for i in x:
  print(i)

def removerhipotesesincoerentes(hipoteses):
    # Objetivo: Remover hipóteses incoerentes (ex: 'x1' e '¬x1') e duplicadas
    hipoteses_validas = []

    for hipotese in hipoteses:
        # Extrai os nomes base das variáveis (ex: '¬x1' vira 'x1')
        variaveis_base = [termo.replace('¬', '') for termo in hipotese]

        # Se a quantidade de variáveis únicas for igual ao número de termos,
        # não há contradições (ex: x1 e ¬x1) nem elementos repetidos.
        if len(set(variaveis_base)) == len(hipotese):
            hipoteses_validas.append(hipotese)

    return hipoteses_validas

def avalia_hipotese(hipotese, exemplo):
    # objetivo: analisar os termo da hipotese
    for termo in hipotese:
        if termo.startswith("¬"):
            indice = int(termo[2:]) - 1  # Converte ¬x1 -> índice 0
            if exemplo[indice] != 0:
                return False
        else:
            indice = int(termo[1:]) - 1   # Converte x1 -> índice 0
            if exemplo[indice] != 1:
                return False
    return True

def comparadorHipoteses_Estatistico(conjuntotreinamento, hipoteses):
    resultados = []
    exemplos_classe0 = conjuntotreinamento[0]
    exemplos_classe1 = conjuntotreinamento[1]
    total_exemplos = len(exemplos_classe0) + len(exemplos_classe1)

    for hipotese in hipoteses:
        tp = sum(1 for ex in exemplos_classe1 if avalia_hipotese(hipotese, ex))
        fp = sum(1 for ex in exemplos_classe0 if avalia_hipotese(hipotese, ex))
        tn = len(exemplos_classe0) - fp

        acuracia = (tp + tn) / total_exemplos

        resultados.append({
            'Hipotese': hipotese,
            'Acertos_Cls1': tp,
            'Erros_Cls0': fp,
            'Acuracia': round(acuracia, 4)
        })

    return sorted(resultados, key=lambda x: x['Acuracia'], reverse=True)

def geradorA1(n,s):

    exemplos0 = []
    exemplos1 = []

    m0 = rnd.randint(2*n, 5*n)
    m1 = rnd.randint(2*n, 5*n)
    # Definição do range do valor de randomização

    for i in range(m0+m1):
        exemplo = tuple([rnd.randint(0,1) for _ in range(n)])
        # Exemplo = tupla com n dimensão com valores 0 ou 1
        if i % 2 == 0:
          # Se o valor do indice for par, verifica se a tupla esta inserida no conjunto
          # e insere caso não esteja. O mesmo para caso o valor seja ímpar.
            if exemplo not in exemplos1:
                exemplos0.append( exemplo )
        else:
            if exemplo not in exemplos0:
                exemplos1.append( exemplo )
    # Dicionário com os conjuntos
    dados = dict()
    dados[0] = exemplos0
    dados[1] = exemplos1
    return dados



if __name__ == "__main__":

    n = 4
    #Semnte de geração 'aleatória'
    semente = 123

    # Ajuste esta variavel para True, caso voce deseje imprimir os exemplos
    __DEBUGA1__ = True

    rnd.seed(semente)

    conjTreinamento = geradorA1(n, semente)

    hipoteses_geradas = geradorHipoteses(n, 3)

    hipoteses_corretas = removerhipotesesincoerentes(hipoteses_geradas)


    if __DEBUGA1__:

        print(f'n = {n}')
        print(f's = {semente}\n')

        print(f'Classe 0 ({len(conjTreinamento[0])} exemplos):')
        for ex in conjTreinamento[0]:
            print(f'\t{ex}')

        print(f'\nClasse 1 ({len(conjTreinamento[1])} exemplos):')
        for ex in conjTreinamento[1]:
            print(f'\t{ex}')

        print("=== TOP 5 HIPÓTESES por Acurácia Geral (Opção 1) ===")
    res_estatistico = comparadorHipoteses_Estatistico(conjTreinamento, hipoteses_corretas)
    for h in res_estatistico[:5]:
        print(h)